
# Exercise — Field Scouting Report (Generated by chatbot)

# Write a program that prints a scouting report for four fields.
# Each field has a name, a crop growing in it, and a measured weed-coverage percentage. 
# Each crop has one typical weed associated with it. 
# Your program should hold all of this information, then print one line per field stating what is growing there, which weed to expect, how much coverage was measured, and what should be done about it.
# The recommendation depends on the coverage: below your threshold, no spray is needed; moderate coverage calls for a spot spray; heavy coverage calls for a full spray. 
# You choose the threshold values and store them so they can be changed in one place.
# The report line itself must be produced by a function that returns the sentence rather than printing it.
# Sample output - Nordfeld: wheat, expect blackgrass. Coverage 12% - spot spray.
# Your finished program must make use of a variable, a list, a dictionary, an if statement, a for loop, and a function.

Monitered_Fields = [
    {"field": "Green valley","Crop":"Rice", "weed":"Barnyard grass", "weed coverage":43},
    {"field": "Golden view","Crop":"Maize", "weed":"Wild oat", "weed coverage":29},
    {"field": "Max Farm","Crop":"Rye", "weed":"Johnson grass", "weed coverage":67},
    {"field": "Class","Crop":"Barley", "weed":"Cornflower", "weed coverage":3},    
]


def final_report(field, crop, weed, weed_coverage):

    threshold_max = 40                   # Only make one threshold value and adding other value directly in the if/else satement 
    threshold_min = 25                   # Do not give the values directly, if you did add a comment there.
    if weed_coverage < 0 or weed_coverage > 100:
        action = "Not valid"
    elif weed_coverage >= threshold_max:
        action =  "Full spray"
    elif weed_coverage >= threshold_min:    #elif weed_coverage < threshold or weed_coverage <= 25,  
        action = "Spot spraying"            #wrote this line else became a dead branch and giving a false 'action'
    else:
        action = "No spraying"

    return (f"{field}: {crop}, expect: {weed}, weed_coverage: {weed_coverage}% - {action}.") # check for any typos/ no errors but grammatically wrong

for my_fields in Monitered_Fields:
    print(final_report(
        my_fields["field"],
        my_fields["Crop"],
        my_fields["weed"],
        my_fields["weed coverage"]
    ))